import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        colorPalette={<div>colorPalette</div>}
        grid={<div>grid</div>}
        actions={<div>actions</div>}
      />
    </>
  );
};

export default Home;
