import type { NextPage } from "next";
import Head from "next/head";
import { ColorPalette } from "../components/ColorPalette";
import Grid from "../components/Grid";
import Layout from "../components/Layout";
import { Color } from "../models/types";

const createEmptyGrid = (numRows: number, numCols: number): Color[][] =>
  new Array(numRows).fill(new Array(numCols).fill("#fff"));

const Home: NextPage = () => {
  const colors: Color[] = [
    "#fff",
    "#f6dbdb",
    "#f2e3c6",
    "#d3ece1",
    "#c2eec7",
    "#eed2e8",
  ];
  const grid = createEmptyGrid(25, 25);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        colorPalette={<ColorPalette colors={colors} />}
        grid={<Grid grid={grid} />}
        actions={<div>actions</div>}
      />
    </>
  );
};

export default Home;
